config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  devise_for :users
  resources :books, only: [:new, :show, :index, :edit, :create, :destroy, :update]
  resources :users, only: [:show, :edit, :update, :index]
  get 'home/about' => 'homes#about', as: 'about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_one_attached :profile_image

  validates :name, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }
  

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
       profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    flash[:notice] = "Signed in successfully."
    user_path(current_user)
  end

  def after_sign_out_path_for(resource)
    flash[:notice] = "Signed out successfully."
    root_path
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book)
    else
      redirect_to books_path
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :is_matching_login_user, only: [:edit, :update, :destroy]

  def new
    @book = Book.new
  end

  def create
    @books = Book.all
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book)
    else
      render "index"
    end
  end 
 
  def show
    @book = Book.find(params[:id])
    @user = User.find(@book.user_id)
    @new = Book.new
  end

  def index 
    @books = Book.all
    @book = Book.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render "edit"
    end
  end


  private

  def book_params
    params.require(:book).permit(:title, :body, :user_id)
  end

  def is_matching_login_user
    book = Book.find(params[:id])
    unless book.user.id == current_user.id
      redirect_to books_path
    end
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController

def create
  @user = User.new(user_params)
  if @user.save
    flash[:notice] = "Welcome! You have signed up successfully."
    redirect_to root_path
  else
    render :new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update,]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @new = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user)
    else
      render "edit"
    end
  end

  def index
    @users = User.all
    @new = Book.new
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_new.html.erb
<div>
  <h2>New book</h2>
    <%= form_with model: @book, url: books_path, local: true do |f| %>
      <a>Title</a>
      <%= f.text_field :title %>
      <a>Opinion</a>
      <%= f.text_area :body %>
      <div class="actions">
        <%= f.submit "Submit", class:"btn btn-success btn-sm" %>
      </div>
    <% end %>
</div>

app/views/books/edit.html.erb
<div class="contaiaer">
  <div class="row">
    <div class="col-md-5 mx-auto">
      <h2 class="mt3">Editing Book</h2>
      <% if @book.errors.any? %>
        <%= @book.errors.count %>errors prohibited this obj from being saved:
        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %> 
      <%= form_with model: @book do |f| %>
      <div class="field mt-3 ">
        <label for="inputTitle">Title</label><br />
        <%= f.text_field :title, value: @book.title, autofocus: true, id:"inputTitle" %>
      </div>
      <div class="field mt-3 ">
        <label for="inputbody">Opinion</label></br />
        <%= f.text_area :body, value: @book.body, autofocus: true, id:"inputbody"%>
      </div>
      <div class="actions mt-3">
        <%= f.submit "Update Book", class:"btn btn-success btn-sm" %>
        <% end %>
      </div>
      <div class="mt-3">
        <%= link_to "Show", book_path(@book) %> |
        <%= link_to "Back", books_path %>
      </div>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="contaiaer mt-3">
  <% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
    <ul>
      <% @book.errors.full_messages.each do |message| %>
       <li><%= message %></li>
      <% end %> 
    </ul>
  <% end %>
  <div class="row mx-auto">
    <div class="col-md-3">
      <%= render '/show', user: @user %>
    </div>
    <div class="col-md-8 offset-md-1">
    <h1>Books</h1>
    <table class="table table-hover">
      <thead>
        <tr>
          <th></th> 
          <th>Title</th>
          <th>Opinion</th>
        </tr>
      </thead>
      <% @books.each do |book| %>
        <tbody>
          <tr>
            <th>
            <%= link_to(user_path(book.user_id)) do %>
            <%= image_tag(book.user.get_profile_image(100, 100)) %>
            <% end %>
            </th>
            <td><%= link_to book.title, book_path(book.id) %></td>
            <td><%= book.body %></td>
          </tr>
        </tbody>
      <% end %>
    </table>
  </div>
</div>

app/views/books/new.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
 

app/views/books/show.html.erb
<div class="containar mt-3">
<% if @book.errors.any? %>
<%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
     <li><%= message %></li>
    <% end %> 
  </ul>
<% end %>
  <div class="row mx-auto">
    <div class="col-md-3">
      <%= render '/show', user: @user %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2> 
      <table class="table">
        <tbody>
          <tr>
            <th><%= image_tag @book.user.get_profile_image(100, 100) %><br />
                <%= link_to @user.name, user_path(@user) %></th>
            <td><%= @book.title %></td>
            <td><%= @book.body %></td>
            <% if @book.user == current_user %>
              <td><%= link_to "Edit", edit_book_path, class: "btn btn-success btn-sm" %></td>
              <td><%= link_to "Destroy", book_path(@book), class: "btn btn-danger btn-sm", method: :delete, data: { confirm: "本当に消しますか？" } %></td>
            <% end %>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
  <div class="mx-auto">
  <h1 class="fw-bold">Welcome to<i class="fa-solid fa-book"></i>Bookers !!</h1>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
  <div class="mx-auto">
    <h1 class="fw-bold">Welcome to<i class="fa-solid fa-book"></i>Bookers !!</h1>
      <p class="lh-lg">In <i class="fa-solid fa-book"></i>Bookers,</p>
      <p class ="lh-lg">you can share and exchange your opinions, inpressions, and emotions</p>
      <p class ="lh-lg">about various books!</p>
    <div class="d-flex flex-column mx-auto w-auto">
    <% if user_signed_in? %>
      <div class="d-grid gap-2">
        <%= link_to user_path(current_user.id), class: 'btn btn-primary btn-block mb-3', role: 'button' do %>Log in
        <% end %> 
      </div>
      <div class="d-grid gap-2">
        <%= link_to user_path(current_user.id), class: 'btn btn-success btn-block', role: 'button' do %>Sign up
        <% end %>
      </div>
    <% else %>
      <div class="d-grid gap-2">
        <%= link_to new_user_session_path, class: 'btn btn-primary btn-block mb-3', role: 'button' do %>Log in
        <% end %>
      </div>
      <div class="d-grid gap-2">
        <%= link_to new_user_registration_path, class: 'btn btn-success btn-block', role: 'button' do %>Sign up
        <% end %>
      </div>
    <% end %>
  </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/984a14387b.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/"> <p class="text-white bg-dark ">Bookers</p></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" 
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to user_path(current_user.id), class: 'nav-link text-white' do %>
                  <i class="fa-solid fa-house"></i> Home
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to users_path, class: 'nav-link text-white' do %>
                  <i class="fa-solid fa-users"></i> Users
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to books_path, class: 'nav-link text-white' do %>
                  <i class="fa-solid fa-book-open"></i> Books
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-white' do %>
                  <i class="fa-solid fa-right-from-bracket"></i> Log out
                <% end %>
              </li>
              <% else %>
              <li class="nav-item">
                <%= link_to root_path, class: 'nav-link text-white' do %>
                  <i class="fa-solid fa-house"></i> Home
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to about_path, class: 'nav-link text-white' do %>
                  <i class="fa-solid fa-link"></i> About
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to new_user_registration_path, class: 'nav-link text-white' do %>
                  <i class="fa-solid fa-user-plus"></i> Sign up
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to new_user_session_path, class: 'nav-link text-white' do %>
                  <i class="fa-solid fa-right-to-bracket"></i> Log in
                <% end %>
              </li>
              <% end %>
            </ul>
          </dv>
        </div>
      </nav>
    </header>
    
    <main>
      <%= flash[:notice] %>
      <%= yield %>
    </main>

    <footer>
    <div class="container bg-white text-dark mt-5">
      <div class="row">
        <div class="mx-auto"><p>CopyRight Infratop.inc</p></div>
      </div>
    </div>
    </footer>
    
  </body>
</html>

app/views/users/edit.html.erb
<div class="contaiaer">
  <div class="row">
    <div class="col-md-5 mx-auto">
      <h2 class="mt3">User info</h2>
      <% if @user.errors.any? %>
      <%= @user.errors.count %>errors prohibited this obj from being saved:
        <ul>
          <% @user.errors.full_messages.each do |message| %>
           <li><%= message %></li>
          <% end %> 
        </ul>
      <% end %>
      <%= form_with model: @user do |f| %>
      <div class="field mt-3 ">
        <label for="inputName">Name</label><br />
        <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
      </div>
      <div class="sield mt-3">
        <label for="inputImage">Image</label><br />
        <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>  
      </div>
      <div class="field mt-3">
        <label for="inputName">Introduction</label><br />
        <%= f.text_area :introduction, autofocus: true, id:"inputIntroduction"%>
      </div>
      <div class="actions mt-3">
        <%= f.submit "Update User", class:"btn btn-secondary btn-sm" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="contaiaer mt-3">
  <div class="row mx-auto">
    <div class="col-md-3">
      <%= render '/show', user: @user %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th></th>
          </tr>
        </thead>
       <% @users.each do |user| %>
        <tbody>
          <tr>
            <td><%= image_tag user.get_profile_image(100, 100) %></td>
            <td><%= user.name %></td>
            <td><%= link_to "Show", user_path(user) %></td>
          </tr>
        </tbody>
      <% end %>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="containar mt-3">
  <div class="row mx-auto">
    <div class="col-md-3">
      <%= render '/show', user: @user %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover">
        <thead>
          <tr>
            <th></th> 
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        <% @books.each do |book| %>
        <tbody>
          <tr>
            <th>
              <%= link_to(user_path(book.user_id)) do %>
              <%= image_tag(book.user.get_profile_image(100, 100)) %>
              <% end %>
            </th>
            <td><%= link_to book.title, book_path(book.id) %></td>
            <td><%= book.body %></td>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>